---
sudo: required

language: generic

env:
  global:
    COMPOSE_PROJECT_NAME: "python2bootstrap"

services:
  - docker

before_install:
  # Downgrade to specific version of Docker engine
  - sudo apt-get update

  # Build container
  - cd tests && docker-compose up -d
  - docker-compose ps
  - docker images
  - docker ps -a

script:
  # Display Ansible version
  - docker exec --tty python2bootstrap_bastion_1 env TERM=xterm ansible --version

  # Basic role syntax check
  - docker exec --tty python2bootstrap_bastion_1 env TERM=xterm ansible-playbook /etc/ansible/roles/python2-bootstrap/tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook
  - docker exec --tty python2bootstrap_bastion_1 env TERM=xterm ansible-playbook /etc/ansible/roles/python2-bootstrap/tests/test.yml

  # Run the role/playbook again, checking to make sure it's idempotent
  - >
    docker exec python2bootstrap_bastion_1 env TERM=xterm ansible-playbook /etc/ansible/roles/python2-bootstrap/tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Playbook specific tests
  # ...

  # Clean up
  - docker-compose down

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
