FROM ubuntu:16.04

RUN mkdir /var/run/sshd

# Install Ansible
RUN apt-get -qq update && \
DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server iproute2

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

ENV DEBIAN_FRONTEND noninteractive
